In [ ]:
import numpy as np
import time

In [ ]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
a = np.random.rand(1000000) # Here, inside the small parenthesis dimension is shown
b = np.random.rand(1000000)
c = 0

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized Version " + str(1000*(toc-tic)) + " ms") # tin oota nai string so that we can concatenate using "+" symbol.
# Yes, you can write str() inside print(), but its primary purpose is type conversion to
# allow string concatenation (+), not for formatted output in the modern sense.
# Here, we have multiplied by one thousand for milli seconds.

c = 0
tic = time.time()
for i in range(1000000):
  c += a[i] * b[i]
toc = time.time()

print(c)
print("For Loop " + str(1000 * (toc - tic)) + " ms")

249753.20361522672
Vectorized Version 0.9391307830810547 ms
249753.20361522268
For Loop 519.8705196380615 ms


# Broadcasting Revision

In [ ]:
var = np.array([[56.0, 0.0, 8.0, 68.0],
                [0.0, 8.5, 78.0, 89.0],
                [6.0, 78.0, 89.0, 67.0]])
print(var)
print(var.shape)

[[56.   0.   8.  68. ]
 [ 0.   8.5 78.  89. ]
 [ 6.  78.  89.  67. ]]
(3, 4)


In [ ]:
total = var.sum(axis = 0) # It adds vertically.
print(total)
print(total.shape)

[ 62.   86.5 175.  224. ]
(4,)


In [ ]:
percentage = 100* var / total
print(percentage)

[[90.32258065  0.          4.57142857 30.35714286]
 [ 0.          9.8265896  44.57142857 39.73214286]
 [ 9.67741935 90.1734104  50.85714286 29.91071429]]


In [ ]:
#  Or we can also do as below
percentage = 100* var / total.reshape(1, 4)
print(percentage)

[[90.32258065  0.          4.57142857 30.35714286]
 [ 0.          9.8265896  44.57142857 39.73214286]
 [ 9.67741935 90.1734104  50.85714286 29.91071429]]


In [ ]:
arr = np.random.randint(0, 10, size = 5)
print(arr)
print(arr.shape)
# We can see that arr is a Rank 1 array.

[7 2 0 9 4]
(5,)


In [ ]:
print(arr.T)
print(arr *arr.T)
print(np.dot(arr, arr.T))
# Here, .T means transpose.

[7 2 0 9 4]
[49  4  0 81 16]
150


In [ ]:
# Now let's take a Rank 2 array
arr2 = arr.reshape(1,5)
print(arr2)
print(arr2.T)
print(arr2 * arr2.T)
print(np.dot(arr2, arr2.T))

[[7 2 0 9 4]]
[[7]
 [2]
 [0]
 [9]
 [4]]
[[49 14  0 63 28]
 [14  4  0 18  8]
 [ 0  0  0  0  0]
 [63 18  0 81 36]
 [28  8  0 36 16]]
[[150]]


In [ ]:
def lol():
  arr9 = np.array([[2, 1], [1, 3]])
  print(arr9 * arr9)

lol()

[[4 1]
 [1 9]]


In [ ]:
def lol():
    # Use probabilities (between 0 and 1)
    y_hat = np.array([0.9, 0.1]) # Predictions
    y = np.array([1, 0])         # Actual labels (cat=1, non-cat=0)

    # Vectorized cost calculation
    # Note: We usually divide by m (number of examples) to get the average
    m = y.shape[0]
    print(y.shape)
    print(m)
    cost = (-1/m) * np.sum(y * np.log(y_hat) + (1-y) * np.log(1-y_hat))

    print(f"Cost: {cost}")
    print(f"Shape: {cost.shape}")

lol()

(2,)
2
Cost: 0.10536051565782628
Shape: ()
