In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from keras.utils import plot_model
print(tf.__version__)

2.19.0


In [ ]:
tf.random.set_seed(42) # Setting a global seed
a1 = tf.random.uniform([3,2], minval=4, maxval=10)
a2 = tf.random.uniform([3,2], minval=4, maxval=10)
print(a1)
print(a2)
tf.random.set_seed(42) # Reseting the global seed
b1 = tf.random.uniform([3,2], minval=4, maxval=10)
b2 = tf.random.uniform([3,2], minval=4, maxval=10)
print(b1)
print(b2)
# so here a1 = b1 and a2 = b2

####INTUITION####
# Think of tf.random.set_seed() like rewinding a playlist:
# First play → song1 = a1, song2 = a2.
# Reset → playlist starts over → song1 = b1, song2 = b2.
# That’s why the pairs match.

tf.Tensor(
[[7.9873724 6.646041 ]
 [6.1172953 6.7868953]
 [4.2019625 8.108034 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[8.127348  6.9068727]
 [9.585966  5.513122 ]
 [8.386924  9.35541  ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[7.9873724 6.646041 ]
 [6.1172953 6.7868953]
 [4.2019625 8.108034 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[8.127348  6.9068727]
 [9.585966  5.513122 ]
 [8.386924  9.35541  ]], shape=(3, 2), dtype=float32)


In [ ]:
# Now for Generator class
gen1 = tf.random.Generator.from_seed(42) # Intuition think of 42 as a playlist of song
gen2 = tf.random.Generator.from_seed(42) # 42 is a playlist of song
z1 = gen1.uniform([3,2], minval=4, maxval=10) # it gives first song of the playlist
z2 = gen1.uniform([3,2], minval = 4, maxval = 10) # it gives second song of the playlist
z3 = gen2.uniform([3,2], minval=4, maxval=10) # it also gives first song of the same playlist
print(z1)
print(z2)
print(z3)


tf.Tensor(
[[8.496068  8.413718 ]
 [6.7138476 6.942389 ]
 [5.13359   7.1216516]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[8.588749 4.230728]
 [9.104185 5.246913]
 [8.271214 9.306352]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[8.496068  8.413718 ]
 [6.7138476 6.942389 ]
 [5.13359   7.1216516]], shape=(3, 2), dtype=float32)


In [ ]:
##DECORATOR###
def decorator(func):
  def wrapper():
    print("Start")
    func()
    print("End")
  return wrapper

@decorator
def hello():
  print("Hello World")
# So the wrapper delays the execution of the decorated function until it’s actually called.
# Without the wrapper, your function runs at decoration time, not at call time.hello()

In [ ]:
import time

def add_tf_uniform(x, y):
    return x + y

@tf.function
def add_tf_deco_uniform(x, y):
    return x + y

x = tf.random.uniform([1000, 1000])
y = tf.random.uniform([1000, 1000])

# Without tf.function
start = time.time()
for _ in range(100):
    add_tf_uniform(x, y)
end = time.time()
print("Without tf.function decorator time =", end - start)

# With tf.function
start = time.time()
for _ in range(100):
    add_tf_deco_uniform(x, y)
end = time.time()
print("With tf.function decorator time =", end - start)

# add_tf_uniform: runs eagerly (Python executes line by line).
# add_tf_deco_uniform: runs as a TensorFlow graph (compiled once, reused).
# First call of add_tf_deco_uniform might be a little slower (graph tracing).
# But repeated calls are faster compared to eager execution.

Without tf.function decorator time = 0.09158086776733398
With tf.function decorator time = 0.2473618984222412


EXPANDING THE DIMENSION OF TENSOR

In [ ]:
rank_2_tensor = tf.random.Generator.from_seed(7)
random2 = rank_2_tensor.uniform([2,3], minval= 10, maxval= 90)
random2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[41.946266, 72.72571 , 64.30412 ],
       [68.71672 , 54.16355 , 18.758812]], dtype=float32)>

In [ ]:
##Now expanding##
random3 = random2[:,:, tf.newaxis]
random3

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[41.946266],
        [72.72571 ],
        [64.30412 ]],

       [[68.71672 ],
        [54.16355 ],
        [18.758812]]], dtype=float32)>

In [ ]:
const = tf.constant([1,2,3])
const

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
variable = tf.Variable([1,2,3])
variable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

TRANSPOSE PRACTICE

In [ ]:
tensor = tf.constant([
                      [[1,2,3]
                      ],
                      [[7,8,9]
                       ]
                      ])
print(tensor)
print(tf.transpose(tensor, perm = None))


tf.Tensor(
[[[1 2 3]]

 [[7 8 9]]], shape=(2, 1, 3), dtype=int32)
tf.Tensor(
[[[1 7]]

 [[2 8]]

 [[3 9]]], shape=(3, 1, 2), dtype=int32)


In [ ]:
A = tf.constant([3,4,5])
B = tf.constant([1,2,3])
print(tf.concat([A,B],axis = 0)) # axis = 0 means concatenation
# print(tf.concat([A, B], axis = 1)) # It throws error
# Rule of thumb:
# concat joins along an existing axis → axis must be in [-rank, rank).
# For 1D tensors, that’s only 0 (or -1).
# To create a new axis, use stack (or expand_dims + concat).

tf.Tensor([3 4 5 1 2 3], shape=(6,), dtype=int32)


In [ ]:
print(A.shape)
A = tf.expand_dims(A, axis = 0)
print(A)
B = tf.expand_dims(B, axis = 0)
print(B)
print(tf.concat([A,B], axis = 0)) # it means row_wise concatenation
print(tf.concat([A,B], axis = 1)) # it means column_wise concatenation


(3,)
tf.Tensor([[3 4 5]], shape=(1, 3), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[3 4 5]
 [1 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor([[3 4 5 1 2 3]], shape=(1, 6), dtype=int32)


In [ ]:
### NUMPY random.randint ###
np.random.randint(0,9, size = 4) # NOTE: By default the size is one


array([8, 5, 6, 8])

In [ ]:
### NESTED LIST COMPREHENSION ###
# Using nested list comprehension to create a random numpy array of 3 rows

np.random.seed(42) # Using seed for reproducibility
random = [[np.random.randint(0,9) for _ in range(4)] for _ in range(3)]
print(random)

[[6, 3, 7, 4], [6, 2, 6, 7], [4, 3, 7, 7]]


In [ ]:
tensor = tf.constant(random)
print(tensor)

tf.Tensor(
[[6 3 7 4]
 [6 2 6 7]
 [4 3 7 7]], shape=(3, 4), dtype=int32)


In [ ]:
# Numpy Train, Test split
np.random.seed(42) # Using seed for reproducibilty
arr = np.array(np.random.randint(0,9, size = (7,4))) # size is used to define shape
print(arr)

[[6 3 7 4]
 [6 2 6 7]
 [4 3 7 7]
 [2 5 4 1]
 [7 5 1 4]
 [0 5 8 0]
 [2 6 3 8]]


In [ ]:
### TO SHUFFLE A NUMPY ARRAY ###

# *** METHOD 1 ***
np.random.seed(42) # Using seed for reproducibility
shuffled_arr = np.random.permutation(arr)
print(shuffled_arr)

# *** METHOD 2 ***
# Converting numpy array into pandas Dataframe
df = pd.DataFrame(arr)
print(df.sample(frac = 1, random_state = 42))

[[6 3 7 4]
 [6 2 6 7]
 [0 5 8 0]
 [4 3 7 7]
 [7 5 1 4]
 [2 5 4 1]
 [2 6 3 8]]
   0  1  2  3
0  6  3  7  4
1  6  2  6  7
5  0  5  8  0
2  4  3  7  7
4  7  5  1  4
3  2  5  4  1
6  2  6  3  8


In [ ]:
## For splitting
train, validate, test = np.split(shuffled_arr,[int(0.6 * len(arr)), int(0.8 * len(arr))])
train, validate, test

(array([[6, 3, 7, 4],
        [6, 2, 6, 7],
        [0, 5, 8, 0],
        [4, 3, 7, 7]]),
 array([[7, 5, 1, 4]]),
 array([[2, 5, 4, 1],
        [2, 6, 3, 8]]))

In [ ]:
# Practice
np.random.seed(7)
array = np.random.randint(1,19, size = (2,3,4))
print(array)
tensor1 = tf.constant(array)
print(tensor1)

[[[16  5  4  8]
  [15  9 15 11]
  [ 9  8  7  5]]

 [[17  8 13  1]
  [12  7 13  6]
  [17  1  3 10]]]
tf.Tensor(
[[[16  5  4  8]
  [15  9 15 11]
  [ 9  8  7  5]]

 [[17  8 13  1]
  [12  7 13  6]
  [17  1  3 10]]], shape=(2, 3, 4), dtype=int64)


In [ ]:
# Or we can use tenor flow random module to generate numbers
random = tf.random.Generator.from_seed(42)
tensor = random.uniform(shape = (2,3,4), minval = 1, maxval = 19, dtype = tf.int32) # Using dtype = tf.int32 for integer
print(tensor)

tf.Tensor(
[[[16  4  7 13]
  [13  4 14 10]
  [ 5 16  8  7]]

 [[ 5 14 14 15]
  [ 1 10 17  4]
  [12  4 15  8]]], shape=(2, 3, 4), dtype=int32)


## INDEXING AND SLICING PRACTICE

In [ ]:
tensor[:, 1, :] # As expected

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[13,  4, 14, 10],
       [ 1, 10, 17,  4]], dtype=int32)>

In [ ]:
tensor[:] # As expected

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[16,  4,  7, 13],
        [13,  4, 14, 10],
        [ 5, 16,  8,  7]],

       [[ 5, 14, 14, 15],
        [ 1, 10, 17,  4],
        [12,  4, 15,  8]]], dtype=int32)>

In [ ]:
tensor[:, 1, -1] # I think the output shape will we 1D (2,)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>

# Using the various methods of tf.keras.metrics.MeanAbsoluteError()
In Multiple Batches

In [ ]:
mae = tf.keras.metrics.MeanAbsoluteError()
# Batch 1
y_true_1 = [1,2,3]
y_pred_1 = [1.1, 2.2, 3.3]
mae.update_state(y_true_1, y_pred_1) ####
print(mae.result()) ####
print(mae.result().numpy()) ####

tf.Tensor(0.2, shape=(), dtype=float32)
0.2


In [ ]:
# Batch 2
y_true_2 = [1,2,3]
y_pred_2 = [1.2, 2.2, 3.3]
mae.update_state(y_true_2, y_pred_2)
print(mae.result())
print(mae.result().numpy())

tf.Tensor(0.21666667, shape=(), dtype=float32)
0.21666667


In [ ]:
mae.reset_state() ####
print(mae.result())
print(mae.result().numpy())

tf.Tensor(0.0, shape=(), dtype=float32)
0.0


In [ ]:
mae = tf.keras.metrics.MeanAbsoluteError()
# Batch 1
y_true_1 = [1,2,3]
y_pred_1 = [1.1, 2.2, 3.3]
mae(y_true_1, y_pred_1) # So basically it does two things simultaneously, calls update_state() and result() methods.

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [ ]:
# Batch 2
y_true_2 = [1,2,3]
y_pred_2 = [1.2, 2.2, 3.3]
mae(y_true_2, y_pred_2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.21666666865348816>

# MEAN SQUARED ERROR

# Checking the difference between tf.keras.metrics.MeanSquaredError()
# and tf.keras.losses.MeanSquaredError()

In [ ]:
# Batch 1 using metrics sub-modlule
y_true_1 = tf.constant([1,2,3], dtype = tf.float32)
y_pred_1 = tf.constant([1.1, 2.2, 3.3])

mse_metric = tf.keras.metrics.MeanSquaredError()
mse_metric.update_state(y_true_1, y_pred_1)
# print(mse_metric.result())
print(f"From the metrics sub-module MSE: {mse_metric.result().numpy()}")

# Now for the same Batch 1 we are using losses sub-module
mse_loss = tf.keras.losses.MeanSquaredError()
loss = mse_loss(y_true_1, y_pred_1)
print(f"From the losses sub-module MSE: {loss.numpy()}")

From the metrics sub-module MSE: 0.046666666865348816
From the losses sub-module MSE: 0.046666666865348816


In [ ]:
# Now for the Second Batch of data
# Batch 2 using metrics sub-module
y_true_2 = tf.constant([1,2,3], dtype = tf.float32)
y_pred_2 = tf.constant([1.2, 2.2, 3.3])

mse_metric.update_state(y_true_2, y_pred_2)
print(f"From the metrics sub-module MSE: {mse_metric.result().numpy()}")

# Now using losses sub-module for the same Batch 2
loss2 = mse_loss(y_true_2, y_pred_2)
print(f"From the losses sub-module MSE: {loss2.numpy()}")

# """ FROM THE RESULT WE CAN SEE THAT LOSSES SUB-MODULE IS NOT STORING INTERNAL STATE AND IT IS WORKING ON CURRENT BATCH
#     WHILE, METRICS SUB-MODULE IS SAVING THE INTERNAL STATE AND GIVES ACCUMULATED RESULT. """

From the metrics sub-module MSE: 0.05166666954755783
From the losses sub-module MSE: 0.056666672229766846


🛠️ **TASK:-** DO THE ABOVE BY MAKING A FUNCTION AND A CLASS.

In [ ]:
import numpy as np
array1 = np.linspace(0, 10, 5)
array2 = np.linspace(100,200, 5)
print(array1)
print(array2)

[ 0.   2.5  5.   7.5 10. ]
[100. 125. 150. 175. 200.]


In [ ]:
# Using meshgrid function of numpy
xx, yy = np.meshgrid(array1, array2)
print(xx)
print(xx.shape)
print(yy)
print(yy.shape)

[[ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]]
(5, 5)
[[100. 100. 100. 100. 100.]
 [125. 125. 125. 125. 125.]
 [150. 150. 150. 150. 150.]
 [175. 175. 175. 175. 175.]
 [200. 200. 200. 200. 200.]]
(5, 5)


In [ ]:
xx.ravel(), yy.ravel()


(array([ 0. ,  2.5,  5. ,  7.5, 10. ,  0. ,  2.5,  5. ,  7.5, 10. ,  0. ,
         2.5,  5. ,  7.5, 10. ,  0. ,  2.5,  5. ,  7.5, 10. ,  0. ,  2.5,
         5. ,  7.5, 10. ]),
 array([100., 100., 100., 100., 100., 125., 125., 125., 125., 125., 150.,
        150., 150., 150., 150., 175., 175., 175., 175., 175., 200., 200.,
        200., 200., 200.]))

In [ ]:
np.c_[xx.ravel(), yy.ravel()]

array([[  0. , 100. ],
       [  2.5, 100. ],
       [  5. , 100. ],
       [  7.5, 100. ],
       [ 10. , 100. ],
       [  0. , 125. ],
       [  2.5, 125. ],
       [  5. , 125. ],
       [  7.5, 125. ],
       [ 10. , 125. ],
       [  0. , 150. ],
       [  2.5, 150. ],
       [  5. , 150. ],
       [  7.5, 150. ],
       [ 10. , 150. ],
       [  0. , 175. ],
       [  2.5, 175. ],
       [  5. , 175. ],
       [  7.5, 175. ],
       [ 10. , 175. ],
       [  0. , 200. ],
       [  2.5, 200. ],
       [  5. , 200. ],
       [  7.5, 200. ],
       [ 10. , 200. ]])